### ISSUE TITLE
Ties for mr_method

### ISSUE THREAD

**Issue by DavidBarke** [Tim-TU/weibulltools#49]

**Comment by Tim-TU** [comment]
average ties, i.e. t <- c(1, 1, ...)  rank = 1.5, 1.5, ... or max ties ... rank= 2, 2, ...

**Comment by DavidBarke** [comment]
Maybe we can turn this into an option in estimate_cdf. I guess this applies to the other methods as well or just for mr?

**Comment by Tim-TU** [comment]
There are several methods for handling ties. 

The Nelson-Aalen estimator corresponds to Breslows method, whereas Johson's classical method uses the maximum ranks. 
The error therefore only refers to `mr_method()`. In literature I've seen average ranks or maximum ranks for tied observations. 

We should adopt the `ties.method` argument of the base function `rank`. As a default I would prefer **max** since this is in line with `johnson_method()` ... and for uncensored data both methods should return the same result. But the user should have the possibility to treat the ties individually
